name: Alpha prerelease (dev)
on:
  push:
    branches: [dev]
permissions:
  contents: write
jobs:
  alpha:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Configure git
        run: |
          git config user.name  "version-bot"
          git config user.email "version-bot@users.noreply.github.com"
      - name: Bump to next alpha
        id: bump
        run: |
          TAG=$(./scripts/bump_version.sh prealpha | tail -n1)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Push version commit + tag
        run: |
          git tag -a "$TAG" -m "$TAG"
          git push && git push --tags

