name: Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  format:
    name: Check C# formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Check formatting
        run: dotnet format Godot-Peer-2-Peer-Steam-CSharp.csproj --verify-no-changes
