name: Release candidate (stage)
on:
  push:
    branches: [stage]
permissions:
  contents: write
jobs:
  rc:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Configure git
        run: |
          git config user.name  "version-bot"
          git config user.email "version-bot@users.noreply.github.com"
      - name: Bump to rc
        run: |
          TAG=$(./scripts/bump_version.sh prerc | tail -n1)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Push version commit + tag
        run: |
          git tag -a "$TAG" -m "$TAG"
          git push && git push --tags
      - name: Create GitHub prerelease
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: gh release create "$TAG" --prerelease --title "$TAG" --notes "Release candidate from stage"

