name: publish stage
on:
  workflow_dispatch:
    inputs:
      level:
        description: "SemVer level"
        type: choice
        options: [patch, minor, major, finalize]
        default: finalize
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure on main
        run: git checkout main && git pull
      - name: Configure git
        run: |
          git config user.name  "version-bot"
          git config user.email "version-bot@users.noreply.github.com"
      - name: Bump stable
        run: |
          TAG=$(./scripts/bump_version.sh "${{ inputs.level }}" | tail -n1)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Push version commit + tag
        run: |
          git tag -a "$TAG" -m "$TAG"
          git push && git push --tags
      - name: Create GitHub release
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: gh release create "$TAG" --title "$TAG" --notes "Stable release from main"

