on:
  push:
    branches:
      - dev

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: export game (.NET/C#)
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_mono_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true

      - name: Show export paths (debug)
        run: |
          echo "archives: ${{ steps.export.outputs.archive_directory }}"
          echo "builds:   ${{ steps.export.outputs.build_directory }}"
      
      - name: Upload archives
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ github.ref_name }}-archives
          path: ${{ steps.export.outputs.archive_directory }}/*
      
      - name: Upload raw builds
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ github.ref_name }}-builds
          path: ${{ steps.export.outputs.build_directory }}/*
